name: Git-workflow

on: [push]

jobs:
  run-linting:
    name: Run-linting
    runs-on: ubuntu-latest
    container: node:14.18-alpine

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-server-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: npm i

      - name: Run linting
        run: npm run lint-full
